In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr.ndim)

1


In [5]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1.ndim)

2


In [8]:
arr3=np.array([[[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15]]])

In [9]:
print(arr3.ndim)

3


In [10]:
arr4=np.arange(10,20,2)
print(arr4)

[10 12 14 16 18]


In [11]:
arr5=np.linspace(10,20,4)
print(arr5)

[10.         13.33333333 16.66666667 20.        ]


In [14]:
arr3.dtype

dtype('int32')

In [18]:
arrfl=arr3.astype('float')

In [19]:
arrfl.dtype

dtype('float64')

# Indexing,slicing and iteration

In [26]:
arr=np.arange(24).reshape(6,4)#multiple

In [27]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [34]:
arr[2][1:3]#bracket kai andar kai jo bhi likhe wo subscript khete hai

array([ 9, 10])

In [38]:
arr[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [39]:
arr[4:5,0:2]

array([[16, 17]])