In [1]:
import numpy as np

In [2]:
arr=np.arange(30)

In [3]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [4]:
arr1=arr.reshape(5,6)

In [5]:
arr2=arr.reshape(15,2)

In [6]:
arr3=arr.reshape(10,3)

In [7]:
print(arr1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [42]:
print(arr1[:5:2,1::2])

[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [8]:
print(arr1[0:4,1:5])

[[ 1  2  3  4]
 [ 7  8  9 10]
 [13 14 15 16]
 [19 20 21 22]]


In [18]:
print(arr1[0:6,1:6:2])

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]
 [25 27 29]]


In [19]:
print(arr1[0:6,::2])

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]


In [21]:
print(arr1[0::2,1::2])

[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [22]:
print(arr1[::2,1::2])

[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [27]:
arr1.size

30

In [28]:
arr1.itemsize

4

In [29]:
arr1.ndim

2

In [37]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [59]:
#addition
import numpy as np

new_arr_1 = np.arange(6).reshape(3,2)
new_arr_2 = np.arange(6).reshape(2,3)

In [49]:
new_arr_1>3

array([False, False, False,  True,  True])

In [61]:
new_arr_3 = new_arr_1.dot(new_arr_2)

In [62]:
new_arr_3

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [69]:
print(new_arr_3)

[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]


In [72]:
new_arr_6=new_arr_2.ravel()
print(new_arr_6)#higher dimension sai lower dimention tak transform kardai gai

[0 1 2 3 4 5]


In [75]:
print(new_arr_3.transpose())

[[ 3  9 15]
 [ 4 14 24]
 [ 5 19 33]]


In [76]:
new_arr_7=np.arange(12).reshape(6,2)

In [91]:
new_arr_8=np.arange(12).reshape(6,2)

In [92]:
np.hstack((new_arr_7,new_arr_8))

array([[ 0,  1,  0,  1],
       [ 2,  3,  2,  3],
       [ 4,  5,  4,  5],
       [ 6,  7,  6,  7],
       [ 8,  9,  8,  9],
       [10, 11, 10, 11]])

In [86]:
np.vstack((new_arr_7,new_arr_8))#data different sheet mai ho tab hum use kare gai

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [93]:
np.hsplit(new_arr_7,2)

[array([[ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]]),
 array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]])]

In [94]:
np.vsplit(new_arr_7,2)

[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]])]